### ISSUE TITLE
Dependence of module six

### ISSUE THREAD

**Issue by zdu863** [LSSTDESC/firecrown#65]
CircleCI gives this error message when it runs checks, seems that schwimmbad has a dependence on six and causes this issue.

> Collecting schwimmbad (from -r requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/08/03/3df8857074b9d31756caf37dd6c611fff2e087d23829265771fc81d5bf52/schwimmbad-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ysufplro/schwimmbad/setup.py", line 34, in <module>
        import schwimmbad
      File "/tmp/pip-install-ysufplro/schwimmbad/schwimmbad/__init__.py", line 26, in <module>
        from .serial import SerialPool
      File "/tmp/pip-install-ysufplro/schwimmbad/schwimmbad/serial.py", line 5, in <module>
        from .pool import BasePool
      File "/tmp/pip-install-ysufplro/schwimmbad/schwimmbad/pool.py", line 6, in <module>
        import six
    ModuleNotFoundError: No module named 'six'

**Comment by beckermr** [comment]
To be clear, there seems to be a missing dep in six in the pypi metadata.

**Comment by beckermr** [comment]
Also this issue needs to be made on the schwimbad repo
